In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from keras.layers import Dense,Flatten, Conv2D
from keras.layers import MaxPooling2D, Dropout
from keras.utils import np_utils
import tensorflow as tf
from keras.models import Sequential
from keras.callbacks import ModelCheckpoint
import pickle
from keras.callbacks import TensorBoard

dataset = os.listdir("/content/drive/MyDrive/dataset/")

x = []
x_load = []
y = []
y_load = []

def load_data():
    label = 0 #convert label to number
    for data in dataset:
        current_data = "/content/drive/MyDrive/dataset/" + data
        x = np.load(current_data)
        x = x.astype('float32') / 64
        x = x[0:10000, :] #get first 10000 strokes
        x_load.append(x)

        y = [label for _ in range(10000)]
        label += 1
        y = np.array(y).astype('float32')
        y = y.reshape(y.shape[0], 1)
        y_load.append(y)
    return x_load, y_load

#load data
features, labels = load_data()

#cast type to float32
features = np.array(features).astype('float32')
labels = np.array(labels).astype('float32')

#reduce dimension
features = features.reshape(features.shape[0] * features.shape[1], features.shape[2])
labels = labels.reshape(labels.shape[0] * labels.shape[1], labels.shape[2])

def cnn_model(image_x, image_y):
    num_of_classes = 9
    model = Sequential()
    model.add(Conv2D(32, (3, 3), input_shape=(image_x,image_y,1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='same'))

    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='same'))
    
    model.add(Conv2D(128, (3, 3), input_shape=(image_x,image_y,1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='same'))

    model.add(Conv2D(128, (3, 3), input_shape=(image_x,image_y,1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='same'))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.5))
    
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_of_classes, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    return model

def prepress_labels(labels):
    labels = np_utils.to_categorical(labels)
    return labels

# shuffle data
features, labels = shuffle(features, labels)
labels = prepress_labels(labels)

#image_size = 28
train_x, test_x, train_y, test_y = train_test_split(features, labels, random_state=0, test_size=0.1)
train_x = train_x.reshape(train_x.shape[0], image_size, image_size, 1)
test_x = test_x.reshape(test_x.shape[0], image_size, image_size, 1)

model = keras_model(image_size,image_size)
model.summary()
model.fit(train_x, train_y, validation_data=(test_x, test_y), epochs=3, batch_size=64)
model.save('/content/drive/MyDrive/dataset/quickDrawModel.h5') 

['full_numpy_bitmap_toothbrush.npy', 'full_numpy_bitmap_camera.npy', 'full_numpy_bitmap_banana.npy', 'full_numpy_bitmap_star.npy', 'full_numpy_bitmap_ice cream.npy', 'full_numpy_bitmap_lightning.npy', 'full_numpy_bitmap_fish.npy', 'full_numpy_bitmap_guitar.npy', 'full_numpy_bitmap_birthday cake.npy']
[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 26, 26, 32)       0         
 2D)                                                             
                                                                 
 conv2d_9 (Conv2D)           (None, 24, 24, 64)        184